/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Groups_FrontEnd;

import Groups_Backend.CurrentGroup;
import Groups_Backend.Group;
import Groups_Backend.GroupManager;
import Groups_Backend_Operations.GroupRequestManager;

import Groups_Backend_Operations.GroupSuggestion;
import Groups_Backend_Operations.GroupSuggestionManager;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

import javax.swing.JOptionPane;
import userdatabasemanagement.CurrentUser;
import userdatabasemanagement.User;

/**
 *
 * @author sherrygirguis
 */
public class GroupSuggestionWindow extends javax.swing.JFrame {

    private GroupRequestManager requestManager;
    private GroupSuggestionManager suggestionManager;
    private User thisUser;
    private  DefaultListModel<String> listModel;
    private GroupManager manager;

    /**
     * Creates new form GroupSuggestionWindow
     */
    public GroupSuggestionWindow() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        requestManager = new GroupRequestManager();
        suggestionManager = new GroupSuggestionManager();
        manager=new GroupManager();
        thisUser = CurrentUser.getInstance().getCurrentUser();
        listModel = new DefaultListModel<>();
        update();

    }

    public void update() {
        suggestionManager.generateSuggestions(thisUser);
        for (GroupSuggestion suggestion : suggestionManager.getSuggestions()) {

            listModel.addElement(suggestion.getSuggested().getName());}
            suggestionList.setModel(listModel);
//            suggestionList.revalidate();
//            suggestionList.repaint();
    }
            


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        suggestionList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        SendFriendRequest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(suggestionList);

        jLabel1.setText("Group Suggestions");

        SendFriendRequest.setText("Send Friend Request");
        SendFriendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendFriendRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SendFriendRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(SendFriendRequest)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendFriendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendFriendRequestActionPerformed

         String selectedGroupId = suggestionList.getSelectedValue();
        if (selectedGroupId == null) {
            JOptionPane.showMessageDialog(this, "Select a group first", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Group selectedGroup = getGroupByName(selectedGroupId);
            CurrentGroup.getInstance().setCurrentGroup(selectedGroup);
        }
        if (selectedGroupId == null) {
            JOptionPane.showMessageDialog(null, "Select a group ", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            Group selectedGroup
                    = getGroupByName(selectedGroupId);

            Factory factory = new Factory(manager);

            JFrame window = factory.createWindow(thisUser, selectedGroup);
            if (window == null) {
                JOptionPane.showMessageDialog(this, "You aren't a member of this group");
            } else {
                window.setVisible(true);
            }

        }
        
        boolean found = false;
        String username = JOptionPane.showInputDialog("Choose");

        if (username == null || username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a group");
            return;
        }
        for (GroupSuggestion suggestion : suggestionManager.getSuggestions()) {

            if (username.equals(suggestion.getSuggested())) {
                suggestionManager.acceptGroupSuggestion(suggestion, thisUser);
                found = true;
                update();
                System.out.print("found");
                break;
            }
        }

        if (!found)
        {
              JOptionPane.showMessageDialog(null, "No Group found!", "Error", JOptionPane.INFORMATION_MESSAGE); 
        }
         
    }//GEN-LAST:event_SendFriendRequestActionPerformed

    
       public Group getGroupByName(String name) {
        for (Group g : manager.getGroups()) {
            if (name.equals(g.getName())) {
                return g;
            }
        }
        return null;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupSuggestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupSuggestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupSuggestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupSuggestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupSuggestionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendFriendRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> suggestionList;
    // End of variables declaration//GEN-END:variables
}
