/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Groups_FrontEnd;

import Groups_Backend.CurrentGroup;
import Groups_Backend.Group;
import Groups_Backend.GroupManager;
import Groups_Backend_Operations.GroupRequest;
import Groups_Backend_Operations.GroupRequestManager;
import friendManagment.Backend.FriendRequest;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import userdatabasemanagement.CurrentUser;
import userdatabasemanagement.User;

/**
 *
 * @author sherrygirguis
 */
public class RequestWindow extends javax.swing.JFrame {
    private GroupRequestManager requestManager = new GroupRequestManager();
    private User thisUser = CurrentUser.getInstance().getCurrentUser();
    private GroupManager manager=new GroupManager();
    /**
     * Creates new form RequestWindow
     */
    public RequestWindow() {
        initComponents();
        update();
    }
public void update(){
DefaultListModel<String> listModel = new DefaultListModel<>();
        for (GroupRequest request : requestManager.getRequests()) {
            listModel.addElement(request.getSender().getUsername());}
             requestsList.setModel(listModel);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestsList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        AcceptRequest = new javax.swing.JButton();
        DeclineRequest = new javax.swing.JButton();
        SelectedGroup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(requestsList);

        jLabel1.setText("Group Requests");

        AcceptRequest.setText("Accept Request ");
        AcceptRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptRequestActionPerformed(evt);
            }
        });

        DeclineRequest.setText("Decline Request");
        DeclineRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeclineRequestActionPerformed(evt);
            }
        });

        SelectedGroup.setText("SelectedGroup");
        SelectedGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectedGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AcceptRequest)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(SelectedGroup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeclineRequest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SelectedGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeclineRequest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AcceptRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeclineRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclineRequestActionPerformed
        // TODO add your handling code here:
                boolean found=false;
        String username = JOptionPane.showInputDialog("Choose");

        if (username == null || username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a group");
            return;}
        else{
            if(requestManager.getRequest(thisUser,username)!=null){
            GroupRequest requestToDecline=requestManager.getRequest(thisUser,username);
            requestManager.declineRequest(requestToDecline);
            update();}
            //notificationWindow.loadNotifications();
            
            else JOptionPane.showMessageDialog(null,"No user found!","Error",JOptionPane.INFORMATION_MESSAGE); } 
    }//GEN-LAST:event_DeclineRequestActionPerformed

    private void AcceptRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptRequestActionPerformed
        // TODO add your handling code here:
                 boolean found=false;
        String username = JOptionPane.showInputDialog("Choose");

        if (username == null || username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a group");
            return;}
        else{
            if(requestManager.getRequest(thisUser,username)!=null){
            GroupRequest requestToAccept=requestManager.getRequest(thisUser,username);
            requestManager.acceptRequest(requestToAccept);
            update();}
            //notificationWindow.loadNotifications();
            
            else JOptionPane.showMessageDialog(null,"No user found!","Error",JOptionPane.INFORMATION_MESSAGE); } 
    }//GEN-LAST:event_AcceptRequestActionPerformed

    private void SelectedGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedGroupActionPerformed
        // TODO add your handling code here:
         String selectedGroupId = requestsList.getSelectedValue();
        if (selectedGroupId == null) {
            JOptionPane.showMessageDialog(this, "Select a group first", "Error", JOptionPane.INFORMATION_MESSAGE);}
        else{
            Group selectedGroup = getGroupById(selectedGroupId);
            CurrentGroup.getInstance().setCurrentGroup(selectedGroup);}
    }//GEN-LAST:event_SelectedGroupActionPerformed
public Group getGroupById(String Id){
        for(Group g:manager.getGroups())
           if(Id.equals(g.getGroupId()))
               return g;
        return null;}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptRequest;
    private javax.swing.JButton DeclineRequest;
    private javax.swing.JButton SelectedGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> requestsList;
    // End of variables declaration//GEN-END:variables
}
