/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Search;

import Groups_Backend.Group;
import Groups_Backend.GroupManager;
import Groups_Backend.Member;
import Groups_Backend_Operations.GroupRequestManager;
import Groups_FrontEnd.ViewGroup;
import java.util.List;
import javax.swing.JOptionPane;
import userdatabasemanagement.CurrentUser;
import userdatabasemanagement.User;
import userdatabasemanagement.UserDatabaseManagement;

/**
 *
 * @author Yara
 */
public class SearchGroupWindow extends javax.swing.JFrame {

    /**
     * Creates new form SearchGroupWindow
     */
    private GroupRequestManager groupRequestManager;

    private User currentUser;
    private GroupManager groupManager;
    private Member member;
    private ViewGroup viewGroup;
    
    public SearchGroupWindow() {
        initComponents();
        groupRequestManager = new GroupRequestManager();
        member= new Member();
        
        groupManager = new GroupManager();
        currentUser = CurrentUser.getInstance().getCurrentUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        groupSearchField = new javax.swing.JTextField();
        searchGroupBtn = new javax.swing.JButton();
        groupsComboBox = new javax.swing.JComboBox<>();
        joinGroupBtn = new javax.swing.JButton();
        leaveGroupBtn = new javax.swing.JButton();
        viewGroupBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchGroupBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchGroupBtn.setText("Search Group");
        searchGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGroupBtnActionPerformed(evt);
            }
        });

        groupsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        joinGroupBtn.setText("Join Group");
        joinGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinGroupBtnActionPerformed(evt);
            }
        });

        leaveGroupBtn.setText("Leave Group");
        leaveGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveGroupBtnActionPerformed(evt);
            }
        });

        viewGroupBtn.setText("View Group");
        viewGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGroupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(groupSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(searchGroupBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(groupsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(joinGroupBtn)
                .addGap(18, 18, 18)
                .addComponent(leaveGroupBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewGroupBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchGroupBtn)
                    .addComponent(groupsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinGroupBtn)
                    .addComponent(leaveGroupBtn)
                    .addComponent(viewGroupBtn))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joinGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGroupBtnActionPerformed
        // TODO add your handling code here:
        String selectedGroup = (String) groupsComboBox.getSelectedItem();
        if(selectedGroup!=null){
        Group g = groupManager.getGroupByName(selectedGroup);
        member.requestToJoinGroup(g, currentUser);
        }
        else
            JOptionPane.showMessageDialog(this, "Please select a group to join", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_joinGroupBtnActionPerformed

    private void leaveGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveGroupBtnActionPerformed
        // TODO add your handling code here:
        String selectedGroup = (String) groupsComboBox.getSelectedItem();
        if(selectedGroup!=null){
        Group g = groupManager.getGroupByName(selectedGroup);
        member.leaveGroup(g, currentUser);
        }
        else
            JOptionPane.showMessageDialog(this, "Please select a group to Leave", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_leaveGroupBtnActionPerformed

    private void viewGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGroupBtnActionPerformed
        // TODO add your handling code here:
        String selectedGroup = (String) groupsComboBox.getSelectedItem();
        if(selectedGroup!=null){
             Group g = groupManager.getGroupByName(selectedGroup);
             if(g!=null){
            if(groupManager.isMember(currentUser, g)){
                viewGroup= new ViewGroup(currentUser, g);
            }
            else{
               JOptionPane.showMessageDialog(this, "You're not a member of this group, please join the group first", "Error", JOptionPane.ERROR_MESSAGE);
            }
             }
             else{
                 System.out.println("g is null in ViewBtn");
             }
           
        }
          else
            JOptionPane.showMessageDialog(this, "Please select a group to View", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_viewGroupBtnActionPerformed

    private void searchGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGroupBtnActionPerformed
        // TODO add your handling code here:
        String search = groupSearchField.getText().trim();
        if (!search.isEmpty()) {
            List<Group> groups = groupManager.loadFromFile();
            List<Group> matchingUsers = groups.stream()
                .filter(group -> group.getName().toLowerCase().contains(search.toLowerCase()))
                .toList();
        if (matchingUsers.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No groups found matching your Search", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
           
            groupsComboBox.removeAllItems(); // Clear previous results
            for (Group group : matchingUsers) {
                groupsComboBox.addItem(group.getName()); 
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a group to search for", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_searchGroupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchGroupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchGroupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchGroupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchGroupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchGroupWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField groupSearchField;
    private javax.swing.JComboBox<String> groupsComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton joinGroupBtn;
    private javax.swing.JButton leaveGroupBtn;
    private javax.swing.JButton searchGroupBtn;
    private javax.swing.JButton viewGroupBtn;
    // End of variables declaration//GEN-END:variables
}
