/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Search;

import Groups_Backend.GroupManager;
import friendManagment.Backend.ManageFriendRequests;
import friendManagment.Backend.ManageFriends;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import profilemanagement.ViewProfile;
import userdatabasemanagement.CurrentUser;
import userdatabasemanagement.User;
import userdatabasemanagement.UserDatabaseManagement;


/**
 *
 * @author Yara
 */
public class SearchUserWindow extends javax.swing.JFrame {

    /**
     * Creates new form SearchUserWindow
     */
      private User user;
     private UserDatabaseManagement accountManagement;
     private ManageFriendRequests manageFriendRequest;
     private ManageFriends manageFriends;
     private GroupManager groupManager;
    
    public SearchUserWindow() {
        initComponents();
                this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        
        user = CurrentUser.getInstance().getCurrentUser();

        accountManagement = new UserDatabaseManagement();
        manageFriendRequest= new ManageFriendRequests();
        manageFriends= new ManageFriends();
        groupManager= new GroupManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userSearchField = new javax.swing.JTextField();
        userSearchBtn = new javax.swing.JButton();
        usersComboBox = new javax.swing.JComboBox<>();
        addFriendBtn = new javax.swing.JButton();
        removeFriend = new javax.swing.JButton();
        blockBtn = new javax.swing.JButton();
        viewProfileBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Window");

        userSearchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userSearchBtn.setText("Search User");
        userSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSearchBtnActionPerformed(evt);
            }
        });

        usersComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        usersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersComboBoxActionPerformed(evt);
            }
        });

        addFriendBtn.setText("Add Friend");
        addFriendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendBtnActionPerformed(evt);
            }
        });

        removeFriend.setText("Remove Friend");
        removeFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFriendActionPerformed(evt);
            }
        });

        blockBtn.setText("Block User");
        blockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockBtnActionPerformed(evt);
            }
        });

        viewProfileBtn.setText("View Profile");
        viewProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addFriendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeFriend)
                        .addGap(14, 14, 14)
                        .addComponent(blockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(userSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFriendBtn)
                    .addComponent(removeFriend)
                    .addComponent(blockBtn)
                    .addComponent(viewProfileBtn))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSearchBtnActionPerformed
        // TODO add your handling code here:
         String search = userSearchField.getText().trim();
    if (!search.isEmpty()) {
        // Fetch users from the JSON database
        List<User> users = accountManagement.loadUsers();
        // Filter users based on the query
        List<User> matchingUsers = users.stream()
                .filter(user -> user.getUsername().toLowerCase().contains(search.toLowerCase()))
                .toList();
        if (matchingUsers.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No users found matching your Search", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Populate the JComboBox with matching usernames
            usersComboBox.removeAllItems(); // Clear previous results
            for (User user : matchingUsers) {
                usersComboBox.addItem(user.getUsername()); // Add User object to JComboBox
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please enter a username to search for", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_userSearchBtnActionPerformed

    private void usersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usersComboBoxActionPerformed

    private void blockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockBtnActionPerformed
        // TODO add your handling code here:
       String selectedFriendusername= (String) usersComboBox.getSelectedItem();
        User selectedFriend= accountManagement.getUserByUsername(selectedFriendusername);
        if(selectedFriend!=null){
             System.out.println("SelectedFriend to be blocked username: "+ selectedFriend.getUsername());
             manageFriends.BlockFriend(selectedFriend);
        }
        else
            JOptionPane.showMessageDialog(this, "Please Select a friend to be Blocked", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_blockBtnActionPerformed

    private void addFriendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendBtnActionPerformed
        // TODO add your handling code here:
        String selectedFriendusername= (String) usersComboBox.getSelectedItem();
        User reciever= accountManagement.getUserByUsername(selectedFriendusername);
        if(reciever!=null){
            System.out.println("reciever username: "+ reciever.getUsername());
        manageFriendRequest.sendRequest( CurrentUser.getInstance().getCurrentUser(),reciever);
        }
        else{
           JOptionPane.showMessageDialog(this, "Please Select a User to be added", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addFriendBtnActionPerformed

    private void removeFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFriendActionPerformed
        // TODO add your handling code here:
         String selectedFriendusername= (String) usersComboBox.getSelectedItem();
        User selectedFriend= accountManagement.getUserByUsername(selectedFriendusername);
        if(selectedFriend!=null){
             System.out.println("SelectedFriend to be removed username: "+ selectedFriend.getUsername());
             manageFriends.RemoveFriend(selectedFriend);
        }
        else
            JOptionPane.showMessageDialog(this, "Please Select a friend to be removed", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_removeFriendActionPerformed

    private void viewProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileBtnActionPerformed
        // TODO add your handling code here:
        String selectedFriendusername= (String) usersComboBox.getSelectedItem();
    
        User selectedFriend= accountManagement.getUserByUsername(selectedFriendusername);
         System.out.println("selected username name: "+ selectedFriendusername );
        if(selectedFriend!=null){
          try {
              ViewProfile vp= new ViewProfile(selectedFriend);
              vp.setVisible(true);
          } catch (IOException ex) {
              Logger.getLogger(SearchUserWindow.class.getName()).log(Level.SEVERE, null, ex);
          }}
        else
            JOptionPane.showMessageDialog(this, "Please Select a friend to be removed", "Error", JOptionPane.ERROR_MESSAGE);
        
        
    }//GEN-LAST:event_viewProfileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchUserWindow().setVisible(true);
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFriendBtn;
    private javax.swing.JButton blockBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton removeFriend;
    private javax.swing.JButton userSearchBtn;
    private javax.swing.JTextField userSearchField;
    private javax.swing.JComboBox<String> usersComboBox;
    private javax.swing.JButton viewProfileBtn;
    // End of variables declaration//GEN-END:variables
}
